---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "horo.fullname" . }}-api
  labels:
    {{- include "horo.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "horo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "horo.fullname" . }}-storage-api
  labels:
    {{- include "horo.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage-api
spec:
  type: {{ .Values.storageApi.service.type }}
  ports:
    - port: {{ .Values.storageApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "horo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage-api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "horo.fullname" . }}-ui
  labels:
    {{- include "horo.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "horo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui

{{- if .Values.storageUi.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "horo.fullname" . }}-storage-ui
  labels:
    {{- include "horo.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage-ui
spec:
  type: {{ .Values.storageUi.service.type }}
  ports:
    - port: {{ .Values.storageUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "horo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage-ui
{{- end }} 